EncryptionSalt = ["", ""]

[[Files]]
  Name = "bin"
  Path = "~/bin"
  Exclude = ["tree-sitter-grammars"]

[[Files]]
  Name = "global-python"
  Path = "~/.config/global-python"
  Exclude = ["result"]

[[Files]]
  Name = "fish"
  Path = "~/.config/fish"

[[Files]]
  Name = "hunspell"
  Path = "~/.config/hunspell"

[[Files]]
  Name = "nix"
  Path = "~/.config/nix"

[[Files]]
  Name = "nixpkgs"
  Path = "~/.config/nixpkgs"

[[Files]]
  Name = "peaclock"
  Path = "~/.config/peaclock"

[[Files]]
  Name = "run-or-raise"
  Path = "~/.config/run-or-raise"

[[Files]]
  Name = "extensions"
  Path = "~/.local/share/gnome-shell/extensions"

[[Files]]
  Name = "burn-my-windows"
  Path = "~/.config/burn-my-windows"

[[Commands]]
  Name = "gnome-settings"
  Backup = "dconf dump /"
  Restore = "dconf load -f /"

[[Commands]]
  Name = "flatpak"
  Backup = "flatpak list --columns=ref --app | tail -n +1"
  Restore = "xargs flatpak install -y --noninteractive --or-update"
