format = """
$os\
$directory\
[> ]()
"""

right_format = """
$shell\
${custom.other}\
$hostname\
$nix_shell\
$git_branch$git_status\
"""

add_newline = false
palette = "catppuccin_mocha"

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[os]
format = "[ $symbol ]($style)"
style = "fg:green"
disabled = false

[directory]
style = "fg:blue"
format = "[ $path ]($style)"
truncation_length = 1
truncation_symbol = ""

[os.symbols]
Ubuntu = ""
Fedora = ""
NixOS = ""

[git_branch]
symbol = ""
style = "fg:sky"
format = '([│](fg:overlay0)[ $symbol $branch ]($style))'

[git_status]
style = "fg:sky"
format = '([$all_status$ahead_behind ]($style))'
stashed = '\$$count'
ahead = "⇡$count"
behind = "⇣$count"
up_to_date = ""
diverged = "⇕$count"
conflicted = "=$count"
deleted = "✘$count"
renamed = "»$count"
modified = "!$count"
staged = "+$count"
untracked = "?$count"
typechanged = ""

[nix_shell]
symbol = ""
style = "fg:red"
format = "[│](fg:overlay0)[ $symbol $state ]($style)"

[hostname]
ssh_symbol = ""
style = "fg:peach"
format = "[│](fg:overlay0)[ $ssh_symbol $hostname ]($style)"

[shell]
disabled = false
style = "fg:lavender"
format = '[ $indicator ]($style)'
bash_indicator = "Bash"
fish_indicator = "Fish"
zsh_indicator = "ZSH"

[custom.other]
command = "echo $STARSHIP_CUSTOM_SEGMENT"
style = "fg:mauve"
format = '[│](fg:overlay0)[ $output ]($style)'
when = 'env | grep STARSHIP_CUSTOM_SEGMENT'
shell = ["bash", "--noprofile", "--norc"]
