---
- name: Fedora Silverblue Setup
  hosts: localhost
  gather_facts: true

  tasks:
    ################################################################################
    ##                                                                            ##
    ##                             Ensure Repositories                            ##
    ##                                                                            ##
    ################################################################################

    - name: Enable RPM Fusion repository
      become: true
      community.general.rpm_ostree_pkg:
        name:
          - https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts.distribution_major_version }}.noarch.rpm
          - https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_facts.distribution_major_version }}.noarch.rpm
        state: present

    - name: Install Ghostty COPR repo (scottames)
      ansible.builtin.get_url:
        url: https://copr.fedorainfracloud.org/coprs/scottames/ghostty/repo/fedora-{{ ansible_facts.distribution_major_version }}/scottames-ghostty-fedora-{{ ansible_facts.distribution_major_version }}.repo
        dest: /etc/yum.repos.d/scottames-ghostty.repo
        mode: '0644'
      become: true

    - name: Add the flathub flatpak repository remote
      become: true
      community.general.flatpak_remote:
        name: flathub
        flatpakrepo_url: https://dl.flathub.org/repo/flathub.flatpakrepo
        state: present

    ################################################################################
    ##                                                                            ##
    ##                              Install Packages                              ##
    ##                                                                            ##
    ################################################################################

    - name: Install core packages
      become: true
      community.general.rpm_ostree_pkg:
        name:
          - distrobox
          - ghostty
          - glibc-langpack-en
          - glibc-langpack-fr
          - glibc-langpack-pt
          - neovim
        state: present
        apply_live: true

    ################################################################################
    ##                                                                            ##
    ##                   Ensure Services Are Enabled And Running                  ##
    ##                                                                            ##
    ################################################################################

    - name: Enable and start services
      become: true
      ansible.builtin.service:
        name: "{{ item }}"
        enabled: true
        state: started
      loop:
        - avahi-daemon
        - firewalld
        - tuned

    - name: Ensure SELinux is enabled and enforcing
      become: true
      ansible.posix.selinux:
        policy: targeted
        state: enforcing

    ################################################################################
    ##                                                                            ##
    ##                             Configure Firewall                             ##
    ##                                                                            ##
    ################################################################################

    - name: Set default zone to 'public'
      ansible.builtin.command: firewall-cmd --set-default-zone=public
      register: default_zone_set
      changed_when:
        - '"ZONE_ALREADY_SET" not in default_zone_set.stderr'

    - name: Gather firewalld facts
      ansible.posix.firewalld_info:
        zones:
          - public
      register: fi_result

    - name: Remove all existing ports from public zone
      ansible.posix.firewalld:
        zone: public
        port: "{{ item[0] }}/{{ item[1] }}"
        state: disabled
        permanent: true
        immediate: true
      loop: "{{ fi_result.firewalld_info.zones.public.ports | default([]) }}"

    - name: Remove all existing services from public zone
      ansible.posix.firewalld:
        zone: public
        service: "{{ item }}"
        state: disabled
        permanent: true
        immediate: true
      loop: "{{ fi_result.firewalld_info.zones.public.services | default([]) }}"

    - name: Ensure required services are enabled in public zone
      ansible.posix.firewalld:
        zone: public
        service: "{{ item }}"
        state: enabled
        permanent: true
        immediate: true
      loop:
        - ssh
        - mdns
        - dhcpv6-client

    ################################################################################
    ##                                                                            ##
    ##                               Configure tuned                              ##
    ##                                                                            ##
    ################################################################################

    - name: Configure tuned
      become: true
      ansible.builtin.command: tuned-adm auto_profile
      register: tuned_configured

    ################################################################################
    ##                                                                            ##
    ##                                 Install Nix                                ##
    ##                                                                            ##
    ################################################################################

    - name: Ensure ~/.config/nix-toolbox exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/nix-toolbox"
        state: directory
        mode: "0755"

    - name: Create home-manager.skipped marker
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/nix-toolbox/home-manager.skipped"
        state: touch
        mode: "0644"

    - name: List existing toolbox containers
      ansible.builtin.command: toolbox list --containers
      register: toolbox_list
      changed_when: false

    - name: Create distrobox container (ghcr.io/thrix/nix-toolbox:42)
      ansible.builtin.command: distrobox create --yes --image ghcr.io/thrix/nix-toolbox:42 --name nix-toolbox
      when: "'nix-toolbox' not in toolbox_list.stdout"

    - name: Ensure ~/.local/bin exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: "0755"

    - name: Ensure ~/.local/share/bin exists
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/share/bin"
        state: directory
        mode: "0755"

    - name: Install distrobox-reexport helper script
      ansible.builtin.copy:
        dest: "{{ ansible_env.HOME }}/.local/share/bin/distrobox-reexport"
        mode: "0755"
        content: |
          #!/usr/bin/env bash
          distrobox enter nix-toolbox -- bash -lc 'find ~/.local/bin/       -type f -exec distrobox-export -d -b {} \;'
          distrobox enter nix-toolbox -- bash -lc 'find ~/.nix-profile/bin/ -type f -exec distrobox-export --bin {} --export-path ~/.local/bin \;'
          distrobox enter nix-toolbox -- bash -lc 'find ~/.nix-profile/bin/ -type l -exec distrobox-export --bin {} --export-path ~/.local/bin \;'
      notify: Run distrobox re-export
      changed_when: true

    ################################################################################
    ##                                                                            ##
    ##                                Configure Nix                               ##
    ##                                                                            ##
    ################################################################################

    - name: Configure nix
      ansible.builtin.command: "{{ item }}"
      loop:
        - nix-channel --add https://github.com/nix-community/home-manager/archive/release-25.11.tar.gz home-manager
        - nix-channel --add https://nixos.org/channels/nixos-25.11 nixos
        - nix-channel --add https://nixos.org/channels/nixpkgs-unstable nixpkgs
        - nix-channel --update
      notify: Run distrobox re-export
      changed_when: true

    ################################################################################
    ##                                                                            ##
    ##                              Restore Dotfiles                              ##
    ##                                                                            ##
    ################################################################################

    - name: Clone my dotfiles
      ansible.builtin.git:
        repo: https://github.com/acristoffers/dotfiles
        dest: ~/Developer/GitHub/dotfiles

    - name: Install dbkp's dependencies
      ansible.builtin.command: distrobox enter nix-toolbox -- bash -lc 'sudo dnf --refresh -y install dconf'

    - name: Run dbkp restore from dotfiles directory
      ansible.builtin.command: nix run github:acristoffers/dbkp -- restore
      args:
        chdir: ~/Developer/GitHub/dotfiles
      register: dbkp_restore
      changed_when: dbkp_restore.rc == 0
      failed_when: dbkp_restore.rc != 0

    - name: Run home-manager installation
      ansible.builtin.command: nix run home-manager/release-25.11 -- init --switch ~/.config/nix/home-manager
      register: hm
      changed_when: hm.rc == 0
      failed_when: hm.rc != 0
      notify: Run distrobox re-export

  handlers:
    - name: Run distrobox re-export
      ansible.builtin.command: "{{ ansible_env.HOME }}/.local/share/bin/distrobox-reexport"
