bind = $mod,        A,         exec, dms ipc call widget toggle launcherButton
bind = $mod,        space,     exec, dms ipc call widget toggle launcherButton
bind = $mod,        semicolon, exec, dms ipc call clipboard toggle
bind =,             F12,       exec, dms ipc call widget toggle notificationButton
bind = Super,       C,         exec, dms ipc call widget toggle controlCenterButton
bind = Super Shift, C,         exec, dms ipc call inhibit toggle
bind = Super Shift, L,         exec, dms ipc call lock lock
bind = Super,       comma,     exec, dms ipc call settings open

# Audio Controls
bindel =, XF86AudioRaiseVolume, exec, dms ipc call audio increment 5
bindel =, XF86AudioLowerVolume, exec, dms ipc call audio decrement 5
bindl =,  XF86AudioMute,        exec, dms ipc call audio mute

# Media Controls
bindl = , XF86AudioPlay, exec, dms ipc call mpris playPause
bindl = , XF86AudioNext, exec, dms ipc call mpris next
bindl = , XF86AudioPrev, exec, dms ipc call mpris previous
bindl = , XF86AudioStop, exec, dms ipc call mpris stop

# Brightness Controls
bindel =, XF86MonBrightnessUp,   exec, dms ipc call brightness increment 5
bindel =, XF86MonBrightnessDown, exec, dms ipc call brightness decrement 5
